### ISSUE TITLE
Query builder Fallow 오타

### ISSUE THREAD

**Issue by Sonchaegeon** [semicolonDSM/DDYZD_V2_Backend_Node#73]
https://github.com/semicolonDSM/DDYZD_V2_Backend_Node/blob/22ba772856e9d1bb9bab9aa274f57bd1f02f33b9/src/entity/entity-repository/clubFollowRepository.ts#L19

**Comment by jeongjiwoo0522** [comment]
my mistake

**Comment by jeongjiwoo0522** [comment]
test
